services:

  web:
    build: ./front
    container_name: front-react-new
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true


  php:
    build: ./back
    container_name: laravel-php-new
    volumes:
      - ./back:/var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t /var/www/html/public
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    ports:
      - "9000:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql

# --- Объявление томов ---
volumes:
  mysql_data: